### ISSUE TITLE
Fast way to generate random prime numbers

### ISSUE THREAD

**Issue by MRJCrunch** [miracl/milagro-crypto-c#167]
Hello! Could you help me with generating random prime numbers with milagro?

I need primes with 1024bit size and 2*p +1 must be prime too.

I've tried algorithm from rsa_key_pair function:
        for (;;)
        {

            FF_random(PRIV->p,RNG,HFLEN);
            while (FF_lastbits(PRIV->p,2)!=3) FF_inc(PRIV->p,1,HFLEN);
            while (!FF_prime(PRIV->p,RNG,HFLEN))
                FF_inc(PRIV->p,4,HFLEN);

            FF_copy(p1,PRIV->p,HFLEN);
            FF_dec(p1,1,HFLEN);

            if (FF_cfactor(p1,e,HFLEN)) continue;
            break;
        }

but it's very slow (generation of prime number requires few seconds). For my specific case I need about 500-1000 iterations to check that 2*p +1 is also prime. It usual requires 15-30 minutes. Similar code based on OpenSSL requires only 15-30 seconds.

Maybe you could tell me a better(faster) algorithm for generating primes with milagro-crypto-c library?

Also looks like there is something wrong with FF_prime function. It works only when amount of BIG in FF is a power of 2.

**Comment by AlessandroBudroni** [comment]
Hi MRJCruch,

such algorithm has been designed only to generate primes for RSA cryptosystem, so probably it is not the best method to generate "safe primes", i.e. primes of the form 2p+1.

If you are looking for other implementations of primality-test algorithms I suggest to look at the MIRACL library https://github.com/miracl/MIRACL/
