### ISSUE TITLE
amcl and milagro-crypto-c differences

### ISSUE THREAD

**Issue by vimmerru** [miracl/milagro-crypto-c#177]
Could you explain the difference between amcl and milagro-crypto-c repos? What library should I use as elliptic curve crypto backend?

**Comment by AlessandroBudroni** [comment]
AMCL is the "golden crypto-library" that includes code in different languages: C, GO, JAVA, JS, RUST, SWIFT.
Milagro-Crypto-C basically consists in the C code of AMCL with the addition of an higher testing coverage and some tools. So if you are thinking to write code in C probably Milagro-Crypto-C is the best solution.
