### ISSUE TITLE
Using milagro from C++11

### ISSUE THREAD

**Issue by philipp-cliqz** [miracl/milagro-crypto-c#189]
I'm assuming the library is already built (with a C compiler). To use it from C++, you have to include its header, for example:

```
extern "C" {
  #include <acml.h>
}
```

Problem is that there are some assumptions in "arch.h", which will break if you are not using C99. As far as I have seen, it should work with C++11 (or higher) with very little changes as "<stdint.h>" was also introduced in C++11.

I should be able to provide a pull request but I wanted to check first if there are objections or whether I have overlooked something.

From what I see, this workaround allows to use it from C++11, but it looks more ugly than necessary:
```
extern "C" {
  #define C99
  #include <acml.h>
  #undef C99
}
```

**Comment by kealan** [comment]
Hi Philipp In the past we have been using the code in c++ as you show above for example;

#define C99
extern "C"
{
#include "mpin.h"
#include "randapi.h"
}

We could have "externed" all the functions but we just use the code as is in our c++ projects.

We are in the process of a major upgrade of the code base. We should have the dev branch updated tomorrow. You will now have the ability to support multiple curves / RSA levels in the one exe.

**Comment by philipp-cliqz** [comment]
Thanks for your answer. Then I would rather wait and use the "C99" trick in the meantime.

We also needed a small fix to support Clang and Emscripten. It is not urgent, but if the upgrade is through we could send you a pull request. Than you could have a look and decide whether it makes to include the patches.

**Comment by kealan** [comment]
Clang is something that we should support - we expect a 15% improvement in timings

**Comment by philipp-cliqz** [comment]
a827871f34d728cd1d07c8371c786b471d278200 was the small Emscripten patch that I previously mentioned. Beside that, I did not encounter any problems.

From my side, we can close this one.

**Comment by kealan** [comment]
OK I will close this and thank you for your PRs and feedback.
