### ISSUE TITLE
Commented out calls to ECP_ZZZ_affine in PAIR_ZZZ_ate

### ISSUE THREAD

**Issue by alex-cliqz** [miracl/milagro-crypto-c#196]
Hello,

We upgraded our code from 3.5 to 4, we noticed that the behaviour of pairing operation was not the same, some of our tests were failing. After debugging, we noticed that two calls to ECP[2]_ZZZ_affine in PAIR_ZZZ_ate were commented out in version 4:
```C
    BIG_XXX_norm(n);

    // ECP2_ZZZ_affine(P);
    // ECP_ZZZ_affine(Q);

    FP_YYY_copy(&Qx,&(Q->x));
    FP_YYY_copy(&Qy,&(Q->y));
```
Uncommenting these made our tests pass again. We do not know much of the internals, but we assume this must be some kind of "normalization" that needs to be done before doing the pairing operations. From now on, should we call these before calling PAIR_ate and PAIR_fexp?

Thanks

**Comment by AlessandroBudroni** [comment]
Hi alex,

yes, as you said, with the new version both the inputs of PAIR_ZZZ_ate must be converted to affine with the functions ECP_ZZZ_affine and ECP2_ZZZ_affine.

**Comment by alex-cliqz** [comment]
That was fast. Thanks!
